### ISSUE TITLE
README links to nothing 

### ISSUE THREAD

**Issue by parkerlreed** [alwsl/alwsl#11]
### &raquo; **[Install]() • [FAQ]() • [Modifications ]() • [Support]() • [Contributing]()**

They are formatted as links but lead to nothing. Is documentation planned?

**Comment by turbo** [comment]
What's unclear about "undocumented"? I had no chance to do anything here, this is nowhere near a stable release. Originally there only was a "dev" branch and master was empty. Somehow it has gone "viral" since then, before anything was ready.

I've said this everywhere, but OK, here is it again: _Wait for the release. This is undocumented._.

**Comment by turbo** [comment]
Duplicate of #5
