### ISSUE TITLE
sudo doesn't think the terminal is worthy of tty status

### ISSUE THREAD

**Issue by lf-** [alwsl/alwsl#14]
When I invoke `bash.exe`, and I try to use sudo and enter a password, I get `sudo: no tty present and no askpass program specified`. This is rather unfortunate while trying to not run as root all the time when you can't use sudo.

This can be fixed with NOPASSWD, but it seems like a deeper issue.

**Comment by turbo** [comment]
The current alwsl distro is a root-only system. This has no effect on the Windows system.

In order to use sudo, you have to properly create a linux user:

``` sh
username=myusername # change this
useradd -m -g users $username
usermod -aG bin,daemon,adm,tty,disk,kmem,wheel,ftp,rfkill,http,network,video,audio,storage,scanner,power,dbus $username
passwd $username
```

Then install `sudo` and add the user to sudoers. Exit bash and use the alwsl `user` task to change the default user.

This process is going to be streamlined in the release.

**Comment by turbo** [comment]
Don't report bugs for the current dev preview. See https://github.com/turbo/alwsl/issues/10#issuecomment-247330534
