### ISSUE TITLE
chroot: "Function not implemented"

### ISSUE THREAD

**Issue by ErichDonGubler** [alwsl/alwsl#30]
I know that this isn't an issue with `alwsl` -- but I wanted to create an issue for the people like me who will wonder why many GNU utilities and `pacman` invocations have strange errors like the following:

```bash 
> chroot /tmp
chroot: cannot change root directory to '/tmp': Function not implemented

> pacman -S netcat
# snip
:: Processing package changes...
(1/1) installing gnu-netcat                                              [########################################] 100%
could not change the root directory (Function not implemented)
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/1) Updating the info directory file...
could not change the root directory (Function not implemented)
error: command failed to execute correctly
```

I'm currently on Win10 OS Build 14393.351, Windows 10 Enterprise.

This issue blocks certain functionalities (i.e., `makepkg -si` for things like installing `yaourt`) like one would with a normal Arch system. This is because `chroot` hasn't been implemented yet for the WSL for non-Insider builds. It was implemented in the Fast Ring Insider build 14936, according to a developer's response to user feedback [here](https://wpdev.uservoice.com/forums/266908-command-prompt-console-bash-on-ubuntu-on-windo/suggestions/13631628-please-add-support-for-the-chroot-syscall). Some workarounds have been suggested, like compiling a no-op `chroot`, but these are not safe and can cause some disasters in one's filesystem. I think the best option is to wait until that functionality makes it to the stable Win10 builds.

Do what you want with this issue, but my bet is that it'd be most useful as an open issue until `chroot` comes to a stable Win10 build, which is currently slated for early 2017 release.

**Comment by turbo** [comment]
This should not occur in alwsl. alwsl includes a custom build of pacman, where the library in question has been compiled without the need of chroot.

Note: This does not apply to the chroot program, which is unsupported in alwsl anyway.

**Comment by ErichDonGubler** [comment]
@turbo: Are you saying that this shouldn't be happening? 

I've updated my original post to have some more platform information. I'm currently on Win10 OS Build 14393.351, Windows 10 Enterprise.

**Comment by ErichDonGubler** [comment]
Okay, did a little more research. The problems start when I hit `Y` for an ignored package prompt (`fakeroot` and `pacman` specifically):

``` bash
$ sudo -S pacman -S fakeroot
> :: fakeroot is in IgnorePkg/IgnoreGroup. Install anyway? [Y/n]
```

 `fakeroot` is needed to compile a package like `package-query`, which is in turn necessary for `yaourt`. If I try to `makepkg -sri` on `package-query`, then it fails because it uses `fakeroot` in its build process. It can be argued that I don't need `yaourt`, but I'd really prefer to have it -- having a good AUR helper is one of the reasons I was interested in `alwsl` in the first place!

**Comment by turbo** [comment]
> custom build of pacman
> 
> ignored

When you (literally) ignore the fixes that make the system work, the system tends to stop working. No surprises here.

In order to preserve archlinux compatibility, many libraries are recompiled with WSL support to prevent packaging yet another build of these utils. These packages, as far as they are accessible by pacman, are in the HOLD or IGNORE group for a good reason.

Don't upgrade them, and everything will work fine. When the upstream changes in pacman et al. are important, they'll get rebuild (currently be me - soon automatically), and you can pull the changes via alwsl's (future) update system. Watch this repository and the alwsl-canary one to get notified of the next build.

Cheers.

**Comment by ErichDonGubler** [comment]
@turbo: The problem of trying to use something like `yoaurt` hasn't been resolved yet. How do you plan on handling that? It looks like it will probably be solved when the new release Win10 WSL comes out, which may fix it. I don't mind you closing this issue, but I'd like to get some closure before leaving this be. I'm too interested in it to simply leave it alone. :)

**Comment by turbo** [comment]
What's the problem with using yaourt? It works just fine in alwsl (as is shown in the screenshot in the README).

**Comment by turbo** [comment]
To clarify, alwsl contains fixes for all the issues you mentioned above:
- a custom build of fakeroot (passthrough)
- a custom build of makepgk (root-enabled)
- a custom version of pacman's libs to work around chroot

If you install alwsl, you can install yaourt like on arch without any issues. You must not however, modify any of the fixes applied.

**Comment by erikli** [comment]
@turbo : I actually found that I had to use a commit prior to [a1ba3d3d](https://github.com/alwsl/alwsl/commit/a1ba3d3d1b833c158f776e63e0c84d4de68d50bf) "Switch to bootstrap distro" in order to get pacman and yaourt to work properly. I ran into this when I went to reinstall a previously working ALWSL install and had issues with pacman/yaourt as well. I don't know if there was a missing step to be completed in the install that I was supposed to do. At the time, I didn't report the issue because this software is still pre-release and an official install option (read: not a .bat file) was still incoming, where I figured any step I was missing would be addressed.

@ErichDonGubler: Can you try commit [7e1fe4c91](https://github.com/alwsl/alwsl/commit/7e1fe4c91ab673bfbe257908c8d199c3dacca971) and see if you still have difficulties?

Maybe this will help resolve the issue?

**Comment by turbo** [comment]
I will roll back to the complete distro from bootstrap for now. Insufficient testing on my side.

**Comment by turbo** [comment]
I've switched the download step back to the older version, please pull alwsl again and reinstall. Thanks @erikli for the report.

**Comment by ErichDonGubler** [comment]
@erikli: Things are working smoothly now with 7e1fe4c91. Thanks!
