### ISSUE TITLE
Installation failed. Bash is still ubuntu. Try again.

### ISSUE THREAD

**Issue by kingdevnl** [alwsl/alwsl#74]
C:\Users\MyUserName\Desktop\alwsl-master>alwsl.bat remove
alwsl (warn): This can't be undone.
Proceed and remove rootfs now? [Y,N]?Y
alwsl (info): Successfully removed al+wsl.

C:\Users\MyUserName\Desktop\alwsl-master>alwsl.bat install
alwsl (info): Cleaning old files.
alwsl (info): Installing base lxss fs from trusty server image. This will take A WHILE.
-- Beta feature --
This will install Ubuntu on Windows, distributed by Canonical
and licensed under its terms available here:
https://aka.ms/uowterms

Downloading from the Windows Store... 100%
Extracting filesystem, this will take a few minutes...
Installation successful!
bash: apt-get: command not found
bash: apt-get: command not found
alwsl (info): Downloading alwsl rootfs (this might take a while)...
alwsl (info): Copying rootfs to temporary extraction destination.
bash: line 0: cd: HOME not set
alwsl (info): Unsquashing rootfs.
bash: line 0: cd: HOME not set
alwsl (info): Transforming...
        1 dir(s) moved.
Het systeem kan het opgegeven bestand niet vinden.
Het systeem kan het opgegeven pad niet vinden.
        0 dir(s) moved.
rm: cannot lstat `*.sfs': No such file or directory
rm: cannot remove `tmp/+~JF2094834644136403172.tmp': Permission denied
rm: cannot remove `tmp/+~JF8721547260217048568.tmp': Permission denied
rm: cannot remove `tmp/A27C.tmp.node': Permission denied
rm: cannot remove `tmp/hsperfdata_MyUserName/10656': Permission denied
rm: cannot remove `tmp/hsperfdata_MyUserName/2172': Permission denied
rm: cannot remove `tmp/hsperfdata_MyUserName/5020': Permission denied
rm: cannot chdir from `tmp' to `~nsuA.tmp': Permission denied
alwsl (info): Checking installation success...
alwsl (fail): Installation failed. Bash is still ubuntu. Try again.

**Comment by kentaromiura** [comment]
Got the same issue, the reason is that in your path you already have a bash.exe,
you can see which one you're executing by typing from a command prompt (cmd.exe)
```
where bash
```
in my case I had not one but two results!
One provided by the git bash (since I don't plan to use it from windows anymore I just uninstalled git), and the devkitPro one in its msys folder; 
I just renamed this last one in bash-devkitpro and after that arch installed successfully.

You can also workaround the problem by changing the order in your PATH system variable if you don't wont to remove or rename executables ;)

**Comment by kingdevnl** [comment]
Yea it also shows 2 For me, Thanks also!
