### ISSUE TITLE
Downloading alwsl's rootfs takes ages

### ISSUE THREAD

**Issue by kilbith** [alwsl/alwsl#76]
Title says it all. The download speed on https://cdn.xorable.org/alwsl-june17.sfs is too slow.

**Comment by turbo** [comment]
1. I cannot reproduce this. I can pull the image with more than 90MB/s
2. The file is served by fastly, so the problem is *very* likely on your end.

**Comment by turbo** [comment]
For reference

```text
$ wget https://cdn.xorable.org/alwsl-june17.sfs
--2017-07-30 22:00:07--  https://cdn.xorable.org/alwsl-june17.sfs
Resolving cdn.xorable.org (cdn.xorable.org)... 2400:cb00:2048:1::6812:271d, 2400:cb00:2048:1::6812:261d, 104.18.38.29, ...
Connecting to cdn.xorable.org (cdn.xorable.org)|2400:cb00:2048:1::6812:271d|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 189407232 (181M) [application/octet-stream]
Saving to: 'alwsl-june17.sfs'

alwsl-june17.sfs              100%[================================================>] 180.63M  94.6MB/s    in 1.9s    

2017-07-30 22:00:20 (94.6 MB/s) - 'alwsl-june17.sfs' saved [189407232/189407232]
```

See also https://status.fastly.com/

**Comment by kilbith** [comment]
> The file is served by fastly, so the problem is very likely on your end.

Nope. I did several attempts of download using my web browser, all of them were ~250-300 KB/s continuously. From France.

It always takes ~20-30 min. to download the rootfs through the script. I did the whole process 5 times already.

**Comment by turbo** [comment]
Still, the CDN serves with at least a Gigabit uplink. I can pull this file from three different US regions, Amsterdam and Germany at more or less 100MB/s. So the problem is in the network between Fastly's Edge and your ISP.

1. There's nothing I can do about it.
2. There's probably nothing Fastly can do about it.

The only thing you can do is to report this to them, at support@fastly.com
